name: Action build
run-name: ${{ github.actor }} is runing build on GitHub Actions ðŸš€
on: [push]
jobs:
  Run-Gradle-Build:
    runs-on: Linux
    steps:
      - run: echo "ðŸŽ‰ Building."
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Build project
        run: ./gradlew build -x lint
